version: '2.0'
services:
  app:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      SOURCE_DATABASE_URL: postgresql://dba:qweasd@MSK-REPL-4.ati.dom:5432/dba_test
      TARGET_DATABASE_URL: postgresql://dba:qweasd@MSK-REPL-4.ati.dom:5432/dba_test_1
      RABBITMQ_URL: amqp://user:pass@rabbit:5672
      REDIS_URL: redis://redis
  worker:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      SOURCE_DATABASE_URL: postgresql://dba:qweasd@MSK-REPL-4.ati.dom:5432/dba_test
      TARGET_DATABASE_URL: postgresql://dba:qweasd@MSK-REPL-4.ati.dom:5432/dba_test
      RABBITMQ_URL: amqp://user:pass@rabbit:5672
      REDIS_URL: redis://redis
    restart: always
    command: fogger:consumer
  redis:
    image: redis:4
